<?php
/**
 * @file
 * Module file for WetKit Search.
 */

include_once 'wetkit_search.features.inc';
include_once 'theme/theme.facetapi.inc';

/**
 * Implements hook_views_api().
 */
function wetkit_search_views_api() {
  return array(
    'api' => 3,
    'template path' => drupal_get_path('module', 'wetkit_search') . '/templates',
  );
}

/**
 * Implements hook_page_build().
 */
function wetkit_search_page_build() {
  drupal_add_css(drupal_get_path('module', 'wetkit_search') . '/css/wetkit_search.css', array(
    'group' => CSS_THEME,
    'every_page' => TRUE,
  ));
}

/**
 * Implements hook_css_alter().
 */
function wetkit_search_css_alter(&$css) {
  unset($css[drupal_get_path('module', 'current_search') . '/current_search.css']);
}

/**
 * Implements hook_theme_registry_alter().
 */
function wetkit_search_theme_registry_alter(&$theme_registry) {
  // Theme FacetAPI Templates.
  $theme_registry['facetapi_count']['theme path'] = drupal_get_path('module', 'wetkit_search');
  $theme_registry['facetapi_count']['function'] = 'wetkit_search_facetapi_count';
  $theme_registry['facetapi_count']['final'] = TRUE;

  $theme_registry['facetapi_link_inactive']['theme path'] = drupal_get_path('module', 'wetkit_search');
  $theme_registry['facetapi_link_inactive']['function'] = 'wetkit_search_facetapi_link_inactive';
  $theme_registry['facetapi_link_inactive']['final'] = TRUE;

  $theme_registry['facetapi_link_active']['theme path'] = drupal_get_path('module', 'wetkit_search');
  $theme_registry['facetapi_link_active']['function'] = 'wetkit_search_facetapi_link_active';
  $theme_registry['facetapi_link_active']['final'] = TRUE;

  // Theme Views Exposed Form.
  $theme_registry['views_exposed_form']['path'] = drupal_get_path('module', 'wetkit_search') . '/templates';
  $theme_registry['views_exposed_form']['theme path'] = drupal_get_path('module', 'wetkit_search') . '/templates';
  $theme_registry['views_exposed_form']['final'] = TRUE;
}

/**
 * Implements hook_preprocess_panels_pane().
 */
function wetkit_search_preprocess_panels_pane(&$variables) {
  if (isset($variables['pane']->subtype) && (substr($variables['pane']->subtype, 0, 8) == 'facetapi')) {
    $variables['classes_array'][] = '';
    $variables['title_attributes_array']['class'][] = 'background-accent';
    $variables['content_attributes_array']['class'][] = 'module';
  }
  if (isset($variables['pane']->subtype) && (substr($variables['pane']->subtype, 0, 14) == 'current_search')) {
    $variables['classes_array'][] = '';
    $variables['title_attributes_array']['class'][] = 'background-accent';
    $variables['content_attributes_array']['class'][] = 'module';
  }
}

/**
 * Implements hook_facetapi_facet_info().
 */
function wetkit_search_facetapi_facet_info($searcher_info) {
  $facets = array();
  /*
  // Example Facets.
  $facets['ss_example'] = array(
  'field' => 'ss_example',
  'label' => t('Example'),
  'description' => t('Example Description'),
  'weight' => 10,
  );
  */
  return $facets;
}

/**
 * Implements hook_facet_items_alter().
 */
function wetkit_search_facet_items_alter(&$build, &$settings) {
  if (isset($build['apps']) && ($build['apps']['#path'] == 'search/site/')) {
    if ($settings->facet == "bundle") {
      foreach ($build as $key => $item) {
        if ($key = 'wetkit_page') {
          $build[$key]["#markup"] = t('Content Pages');
        }
      }
    }
  }
}
